# Generated by Django 4.1.5 on 2023-01-12 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('divulgar', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='tag',
            new_name='raca',
        ),
    ]
