# Generated by Django 4.1.5 on 2023-01-12 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('divulgar', '0002_rename_tag_tag_raca'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tag',
            new_name='Raca',
        ),
    ]
